[package]
name = "pixelpwnr-render-test"
version = "0.1.0"
authors = ["Tim Visée <timvisee@gmail.com>"]

[dependencies]
image = "0.18"
gfx = "0.17"
gfx_window_glutin = "0.20"
glutin = "0.12"

[profile.release]
lto = true
