[package]
name = "pixelpwnr-render"
version = "0.1.0"
authors = ["Tim Visée <timvisee@gmail.com>"]

[dependencies]
image = "0.18"
gfx = "0.17"
gfx_window_glutin = "0.20"
glutin = "0.12"
lazy_static = "1.0"
time = "0.1"

# TODO: re-enable this at release 
# [profile.release]
# lto = true
