[package]
name = "pixelpwnr-render-test"
version = "0.1.0"
authors = ["Tim Visée <timvisee@gmail.com>"]

[dependencies]
image = "0.17"
gfx = "0.16"
gfx_window_glutin = "0.16"
glutin = "0.8"

[profile.release]
lto = true
